### ISSUE TITLE
Request for code of the paper entitled "SAME:Skeleton-Agnostic Motion Embedding for Character Animation"

### ISSUE THREAD

**Issue by X-leaners** [sunny-Codes/MotionBuilderScript#1]
Dear @sunny-Codes:
      I am sorry to disturb you in your busy schedule. I am doing research works about motion retargeting recently, which is closely related to your newly published paper entitled "SAME:Skeleton-Agnostic Motion Embedding for Character Animation". Your paper is very interesting and gives me great inspiration. In this paper, the relevant source code website link is provided, but when I clicked, I found that the content had been deleted, so would you please share your source code with me?

**Comment by GuangtaoLyu** [comment]
+1

**Comment by jiayoujiayoujiayoua** [comment]
+1

**Comment by sunny-Codes** [comment]
Dear @X-leaners, @GuangtaoLyu, @jiayoujiayoujiayoua 

Thanks for your attention to our paper and sorry for checking this late.
You can check out our code for the paper here: 
https://github.com/sunny-Codes/SAME

Thank you.
